In [1]:
import numpy as np
import pandas as pd

In [36]:
dfs = []
df=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\BPCL.csv")
df_1=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\BSE.csv")
df_2=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\ETHOS_LTD.csv")
df_3=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\FORTIS.csv")
df_4=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\GLENMARK.csv")
df_5=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\HDFCLIFE.csv")
df_6=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\HINDPETRO.csv")
df_7=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\HINDUUNILVR.csv")
df_8=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\IOC.csv")
df_9=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\JSL.csv")
df_10=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\LT.csv")
df_11=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\M&M.csv")
df_12=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\POWERINDIA.csv")
df_13=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\TATAMOTORS.csv")
df_14=pd.read_csv(r"C:\Users\Dell\Desktop\Research Project\Datasets\TITAN.csv")

In [37]:
df.columns = df.columns.str.strip().str.replace(' ', '')
df_1.columns = df_1.columns.str.strip().str.replace(' ', '')
df_2.columns = df_2.columns.str.strip().str.replace(' ', '')
df_3.columns = df_3.columns.str.strip().str.replace(' ', '')
df_4.columns = df_4.columns.str.strip().str.replace(' ', '')
df_5.columns = df_5.columns.str.strip().str.replace(' ', '')
df_6.columns = df_6.columns.str.strip().str.replace(' ', '')
df_7.columns = df_7.columns.str.strip().str.replace(' ', '')
df_8.columns = df_8.columns.str.strip().str.replace(' ', '')
df_9.columns = df_9.columns.str.strip().str.replace(' ', '')
df_10.columns = df_10.columns.str.strip().str.replace(' ', '')
df_11.columns = df_11.columns.str.strip().str.replace(' ', '')
df_12.columns = df_12.columns.str.strip().str.replace(' ', '')
df_13.columns = df_13.columns.str.strip().str.replace(' ', '')
df_14.columns = df_14.columns.str.strip().str.replace(' ', '')

In [40]:
for df in [df,df_1,df_2,df_3,df_4,df_5,df_6,df_7,df_8,df_9,df_10,df_11,df_12,df_13,df_14]:
    df = df.drop(['series','OPEN','HIGH','LOW','PREV.CLOSE','close','vwap','52WH','52WL','VOLUME','VALUE','Nooftrades'],axis=1)
    df_pivot = df.pivot(index='Company', columns='Date', values='ltp')
    dfs.append(df_pivot)

In [41]:
df1 = df1.pivot(index='Company', columns='Date', values='ltp')

df1 = pd.concat(dfs)

In [42]:
df1

Date,01-Jun-23,02-Jun-23,02-May-23,03-Jul-23,03-May-23,04-Jul-23,04-May-23,05-Jul-23,05-Jun-23,05-May-23,...,26-Jun-23,26-May-23,27-Apr-23,27-Jun-23,28-Apr-23,28-Jun-23,29-May-23,30-Jun-23,30-May-23,31-May-23
Company,,,,,,,,,,,,,,,,,,,,,
BPCL,364.5,359.8,360.6,375.05,360.6,376.8,367.4,385,357,364.3,...,358,364.05,355,359.85,356.3,365.85,362.5,365,360.2,364.6
BSE,571,572,529,668,519.6,673,516.5,679.3,575.05,511.8,...,597.5,535.5,520.8,601,523.5,617,540.55,608.95,542.95,557.2
ETHOS_LTD,"1,259.95","1,279.00","1,301.00","1,442.90","1,308.00","1,484.00","1,288.00","1,496.25","1,277.00","1,290.00",...,"1,284.05","1,249.15","1,209.00","1,305.00","1,300.00","1,363.00","1,258.00","1,445.00","1,220.10","1,224.90"
FORTIS,278.05,276.6,261,313,263.7,313.45,264,315.5,274.75,266.45,...,303.5,287.85,256.9,304.25,261,304.4,280.5,315.5,279.75,275.15
GLENMARK,609.6,614,543,659,543,650.2,545,663.5,616.7,551.25,...,645.5,591.05,553,655.05,563,678,593,677.3,595.2,596.2
HDFCLIFE,581,576.1,544.25,650.7,538.45,648,546,675,573.2,540.6,...,630,577,519.75,664.9,530.45,659.7,578.7,648.5,589,593.3
HINDPETRO,260.25,258.65,252,284.35,256.9,279.4,258,290.05,257,253.9,...,272.25,258.3,250.65,267.5,250.75,269.25,257.5,273.5,256.95,262.65
HINDUNILVR,"2,691.00","2,711.05","2,450.90","2,700.20","2,485.20","2,701.55","2,502.50","2,756.95","2,702.00","2,501.20",...,"2,653.70","2,652.05","2,469.00","2,650.00","2,458.00","2,669.65","2,649.50","2,676.05","2,655.00","2,667.65"
IOC,90.6,89.9,82.05,95.7,82.8,94.55,83.25,95.4,89.45,82.65,...,89.75,90.2,80.5,89.45,81.35,91,90,91.25,90.4,89.9
JSL,292.7,290.05,286,340.5,288.9,342.95,292.4,352,284,291,...,329.85,289,287.5,329,283,332.65,291.15,331.5,282,300.9
LT,"2,209.40","2,236.00","2,387.00","2,456.00","2,355.80","2,463.00","2,363.00","2,472.00","2,269.50","2,379.45",...,"2,375.00","2,218.00","2,305.50","2,389.00","2,360.00","2,424.00","2,227.30","2,475.00","2,212.50","2,212.50"
M&M,"1,319.80","1,343.00","1,234.00","1,471.70","1,235.00","1,467.55","1,230.45","1,477.90","1,394.95","1,213.00",...,"1,398.00","1,277.00","1,224.00","1,401.50","1,225.10","1,397.00","1,325.05","1,456.00","1,327.05","1,316.20"
POWERINDIA,"3,909.90","3,913.00","3,415.05","4,127.25","3,355.00","4,105.50","3,452.00","4,210.00","3,900.00","3,744.00",...,"4,199.00","3,780.10","3,295.00","4,103.00","3,309.05","4,125.00","3,841.00","4,142.00","3,880.00","3,849.00"
TATAMOTORS,534.4,535.1,480.4,591.9,483.7,591.9,481.2,589.9,545.5,477.2,...,568.45,517.8,481,572.75,484.45,586,521,595.2,519.15,525
TITAN,"2,820.00","2,858.00","2,664.95","3,042.00","2,651.00","3,079.00","2,666.20","3,106.80","2,853.80","2,732.00",...,"2,981.00","2,740.25","2,660.40","2,988.90","2,637.00","3,031.00","2,813.95","3,055.00","2,802.00","2,819.00"

In [46]:
df1.iloc[1]

Date
01-Jun-23       571
02-Jun-23       572
02-May-23       529
03-Jul-23       668
03-May-23     519.6
              ...
28-Jun-23       617
29-May-23    540.55
30-Jun-23    608.95
30-May-23    542.95
31-May-23     557.2
Name: BSE, Length: 62, dtype: object

In [53]:
#df2 = df1
#df2.columns = pd.to_datetime(df2.columns, format='%d-%b-%y')
#df2 = df2.reindex(sorted(df2.columns), axis=1)
df2

Date,2023-04-10,2023-04-11,2023-04-12,2023-04-13,2023-04-17,2023-04-18,2023-04-19,2023-04-20,2023-04-21,2023-04-24,...,2023-06-23,2023-06-26,2023-06-27,2023-06-28,2023-06-30,2023-07-03,2023-07-04,2023-07-05,2023-07-06,2023-07-07
Company,,,,,,,,,,,,,,,,,,,,,
BPCL,335.4,338.5,337.5,332.35,335.5,334.4,342.8,343.65,345.65,346.5,...,360.5,358,359.85,365.85,365,375.05,376.8,385,391.2,392
BSE,458,463.6,462.6,459.8,461,467.1,454.9,449.4,449.8,458.3,...,608.1,597.5,601,617,608.95,668,673,679.3,705.4,704.5
ETHOS_LTD,"1,002.00","1,010.00","1,000.60","1,042.60","1,194.00","1,197.00","1,177.05","1,240.00","1,225.00","1,238.00",...,"1,299.65","1,284.05","1,305.00","1,363.00","1,445.00","1,442.90","1,484.00","1,496.25","1,496.50","1,503.40"
FORTIS,255.7,257.2,265,265.35,265,264.95,265.9,265.5,265,265.25,...,305.5,303.5,304.25,304.4,315.5,313,313.45,315.5,321,325.7
GLENMARK,487.3,484.5,491.9,490.1,490.75,505.5,512,511.75,510.2,518.6,...,630.75,645.5,655.05,678,677.3,659,650.2,663.5,669.45,689.15
HDFCLIFE,514,512.9,517.95,531.35,532.9,533,524.95,529.8,513.5,546.15,...,629.8,630,664.9,659.7,648.5,650.7,648,675,660.6,658
HINDPETRO,229,231.4,229.9,225.1,227,228.2,238.7,239.25,240.65,243.45,...,269.45,272.25,267.5,269.25,273.5,284.35,279.4,290.05,301.8,306.35
HINDUNILVR,"2,527.80","2,546.00","2,528.10","2,535.40","2,555.50","2,538.25","2,523.50","2,493.15","2,499.85","2,500.60",...,"2,647.00","2,653.70","2,650.00","2,669.65","2,676.05","2,700.20","2,701.55","2,756.95","2,750.00","2,699.00"
IOC,77.85,77.95,78.15,77.25,77.35,77.95,78.7,78.3,78.15,78.3,...,89.35,89.75,89.45,91,91.25,95.7,94.55,95.4,98.65,99.4
JSL,283.3,276.95,264.8,265.05,263,261.5,260.15,265,268.1,271.45,...,324.6,329.85,329,332.65,331.5,340.5,342.95,352,365,363.2
LT,"2,310.00","2,302.70","2,289.00","2,263.50","2,213.00","2,222.00","2,218.00","2,236.35","2,214.90","2,232.50",...,"2,392.90","2,375.00","2,389.00","2,424.00","2,475.00","2,456.00","2,463.00","2,472.00","2,487.00","2,452.00"
M&M,"1,189.00","1,203.50","1,209.00","1,205.45","1,214.00","1,205.40","1,215.45","1,215.05","1,212.15","1,206.90",...,"1,374.35","1,398.00","1,401.50","1,397.00","1,456.00","1,471.70","1,467.55","1,477.90","1,549.50","1,561.00"
POWERINDIA,"3,160.20","3,143.00","3,140.00","3,130.00","3,085.00","3,100.00","3,045.00","3,199.00","3,238.00","3,239.50",...,"4,100.00","4,199.00","4,103.00","4,125.00","4,142.00","4,127.25","4,105.50","4,210.00","4,307.20","4,241.65"
TATAMOTORS,460.9,459.4,464.95,468.85,472,472.4,469.3,475.5,471.2,474.4,...,560.45,568.45,572.75,586,595.2,591.9,591.9,589.9,601,622.9
TITAN,"2,578.00","2,577.10","2,588.00","2,580.00","2,607.05","2,575.00","2,566.05","2,575.35","2,573.00","2,625.00",...,"2,933.05","2,981.00","2,988.90","3,031.00","3,055.00","3,042.00","3,079.00","3,106.80","3,106.15","3,144.00"

In [54]:
df2.to_csv('3M_data.csv')